# Generated by Django 4.0.5 on 2022-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='decriptions',
            field=models.CharField(default='decriptions', max_length=100),
            preserve_default=False,
        ),
    ]
